import {
  FaHammer, FaWrench, FaTools, FaScrewdriver, FaPencilRuler, FaRuler,
  FaCog, FaCogs, FaBolt, FaPlug, FaLightbulb, FaSnowflake, FaFire,
  FaFaucet, FaTint, FaUmbrella, FaHardHat, FaShieldAlt,
  FaFireExtinguisher, FaMedkit, FaBuilding, FaIndustry, FaRoad,
  FaLayerGroup, FaCube, FaPaintRoller, FaBrush, FaSprayCan, FaTree,
  FaSeedling, FaDoorOpen, FaWindowMaximize,
  FaTruck, FaWarehouse, FaArchive, FaBarcode, FaTags, FaOilCan, FaGasPump,
  FaShoppingCart, FaShoppingBag, FaStore, FaCashRegister, FaGift, FaStar,
  FaTshirt, FaSocks, FaGlasses, FaUserTie,
  FaUtensils, FaCoffee, FaWineGlass, FaBeer, FaAppleAlt,
  FaPizzaSlice, FaCarrot, FaBreadSlice,
  FaSoap, FaToiletPaper, FaBroom, FaHandSparkles,
  FaPills, FaHeartbeat, FaStethoscope, FaBandAid, FaTablets,
  FaDumbbell, FaRunning, FaFutbol, FaBicycle, FaSwimmer, FaGamepad,
  FaMobileAlt, FaTabletAlt, FaTv, FaCamera, FaHeadset,
  FaLaptop, FaMouse, FaHeadphones, FaHdd, FaMemory,
  FaPaw, FaDog, FaCat, FaFish,
  FaCar, FaMotorcycle,
  FaBook, FaPen, FaPencilAlt, FaCalculator, FaPrint,
  FaCouch, FaChair,
  FaHome, FaBaby, FaChild, FaHeart,
  FaBox,
} from 'react-icons/fa'

export function getCategoryIcon(iconName?: string, size = 32): React.ReactNode {
  const key = iconName?.toLowerCase() ?? ''

  const iconMap: Record<string, React.ReactNode> = {
    // Varejo
    store:        <FaStore size={size} />,
    shoppingcart: <FaShoppingCart size={size} />,
    shoppingbag:  <FaShoppingBag size={size} />,
    cashregister: <FaCashRegister size={size} />,
    tags:         <FaTags size={size} />,
    gift:         <FaGift size={size} />,
    star:         <FaStar size={size} />,
    barcode:      <FaBarcode size={size} />,
    // Moda
    tshirt:       <FaTshirt size={size} />,
    socks:        <FaSocks size={size} />,
    glasses:      <FaGlasses size={size} />,
    usertie:      <FaUserTie size={size} />,
    // Alimentação
    utensils:     <FaUtensils size={size} />,
    coffee:       <FaCoffee size={size} />,
    beer:         <FaBeer size={size} />,
    wineglass:    <FaWineGlass size={size} />,
    applealt:     <FaAppleAlt size={size} />,
    carrot:       <FaCarrot size={size} />,
    breadslice:   <FaBreadSlice size={size} />,
    pizzaslice:   <FaPizzaSlice size={size} />,
    // Limpeza
    soap:         <FaSoap size={size} />,
    handsparkles: <FaHandSparkles size={size} />,
    broom:        <FaBroom size={size} />,
    toiletpaper:  <FaToiletPaper size={size} />,
    spray:        <FaSprayCan size={size} />,
    spraycan:     <FaSprayCan size={size} />,
    // Saúde
    pills:        <FaPills size={size} />,
    tablets:      <FaTablets size={size} />,
    heartbeat:    <FaHeartbeat size={size} />,
    stethoscope:  <FaStethoscope size={size} />,
    bandaid:      <FaBandAid size={size} />,
    // Doméstico
    home:         <FaHome size={size} />,
    couch:        <FaCouch size={size} />,
    baby:         <FaBaby size={size} />,
    child:        <FaChild size={size} />,
    heart:        <FaHeart size={size} />,
    // Pets
    paw:          <FaPaw size={size} />,
    dog:          <FaDog size={size} />,
    cat:          <FaCat size={size} />,
    fish:         <FaFish size={size} />,
    // Esportes
    dumbbell:     <FaDumbbell size={size} />,
    running:      <FaRunning size={size} />,
    futbol:       <FaFutbol size={size} />,
    bicycle:      <FaBicycle size={size} />,
    swimmer:      <FaSwimmer size={size} />,
    gamepad:      <FaGamepad size={size} />,
    // Eletrônicos
    mobilealt:    <FaMobileAlt size={size} />,
    tabletalt:    <FaTabletAlt size={size} />,
    tv:           <FaTv size={size} />,
    camera:       <FaCamera size={size} />,
    laptop:       <FaLaptop size={size} />,
    headset:      <FaHeadset size={size} />,
    headphones:   <FaHeadphones size={size} />,
    mouse:        <FaMouse size={size} />,
    hdd:          <FaHdd size={size} />,
    memory:       <FaMemory size={size} />,
    // Automotivo
    car:          <FaCar size={size} />,
    motorcycle:   <FaMotorcycle size={size} />,
    truck:        <FaTruck size={size} />,
    gaspump:      <FaGasPump size={size} />,
    oilcan:       <FaOilCan size={size} />,
    // Papelaria
    book:         <FaBook size={size} />,
    pen:          <FaPen size={size} />,
    pencilalt:    <FaPencilAlt size={size} />,
    calculator:   <FaCalculator size={size} />,
    print:        <FaPrint size={size} />,
    archive:      <FaArchive size={size} />,
    // Construção
    hammer:       <FaHammer size={size} />,
    wrench:       <FaWrench size={size} />,
    tools:        <FaTools size={size} />,
    screwdriver:  <FaScrewdriver size={size} />,
    ruler:        <FaPencilRuler size={size} />,
    measure:      <FaRuler size={size} />,
    cog:          <FaCog size={size} />,
    cogs:         <FaCogs size={size} />,
    bolt:         <FaBolt size={size} />,
    plug:         <FaPlug size={size} />,
    lightbulb:    <FaLightbulb size={size} />,
    snowflake:    <FaSnowflake size={size} />,
    fire:         <FaFire size={size} />,
    faucet:       <FaFaucet size={size} />,
    water:        <FaTint size={size} />,
    umbrella:     <FaUmbrella size={size} />,
    hardhat:      <FaHardHat size={size} />,
    shield:       <FaShieldAlt size={size} />,
    extinguisher: <FaFireExtinguisher size={size} />,
    medkit:       <FaMedkit size={size} />,
    building:     <FaBuilding size={size} />,
    industry:     <FaIndustry size={size} />,
    road:         <FaRoad size={size} />,
    layers:       <FaLayerGroup size={size} />,
    cube:         <FaCube size={size} />,
    paint:        <FaPaintRoller size={size} />,
    brush:        <FaBrush size={size} />,
    tree:         <FaTree size={size} />,
    seedling:     <FaSeedling size={size} />,
    door:         <FaDoorOpen size={size} />,
    window:       <FaWindowMaximize size={size} />,
    warehouse:    <FaWarehouse size={size} />,
    chair:        <FaChair size={size} />,
    // Geral
    box:          <FaBox size={size} />,
  }

  return iconMap[key] ?? <FaBox size={size} />
}
